version: '3'
services:
  simple-app:
    build:
      context: .  # Katalog, w którym znajduje się Dockerfile (aktualny katalog)
      dockerfile: Dockerfile  # Nazwa pliku Dockerfile
    working_dir: /app
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"